classdef TestSegmentCurationSynthetic < matlab.unittest.TestCase
    % Проверка инженерной фильтрации и удаления перекрывающихся участков.

    methods (Test)
        function testCurationAndOverlapRemoval(testCase)
            processedData = makeProcessedData();
            segmentRegistry = makeRegistry();
            settings = makeSettings();

            [curatedSegments, excludedSegments] = copter.validation.curateValidationSegments( ...
                segmentRegistry, processedData, settings);
            [keptSegments, overlapExcluded] = copter.validation.removeOverlappingSegments(curatedSegments, settings);

            testCase.verifyGreaterThan(height(excludedSegments), 0);
            testCase.verifyTrue(any(contains(excludedSegments.exclusion_reason, "малая дисперсия входа")));
            testCase.verifyEqual(height(keptSegments), 1);
            testCase.verifyTrue(any(keptSegments.segment_id == ["good_overlap_a", "good_overlap_b"]));
            testCase.verifyEqual(height(overlapExcluded), 1);
        end
    end
end

function dataTable = makeProcessedData()
t = transpose(0:0.01:12);
dataTable = table();
dataTable.t_s = t;
dataTable.log_file = repmat("synthetic.BIN", numel(t), 1);
dataTable.("RATE.R") = 20 * sin(4 * t);
dataTable.("RATE.P") = 5 * sin(2 * t);
dataTable.("RATE.Y") = 3 * sin(3 * t);
dataTable.("RATE.R_rad_s") = deg2rad(dataTable.("RATE.R"));
dataTable.("RATE.P_rad_s") = deg2rad(dataTable.("RATE.P"));
dataTable.("RATE.Y_rad_s") = deg2rad(dataTable.("RATE.Y"));
dataTable.("RATE.ROut") = 0.2 * sin(4 * t);
dataTable.("RATE.POut") = 0.03 * sin(2 * t);
dataTable.("RATE.YOut") = 0.03 * sin(3 * t);
lowInputMask = t >= 8 & t <= 10;
rout = dataTable.("RATE.ROut");
pout = dataTable.("RATE.POut");
yout = dataTable.("RATE.YOut");
rout(lowInputMask) = 0.001;
pout(lowInputMask) = 0.001;
yout(lowInputMask) = 0.001;
dataTable.("RATE.ROut") = rout;
dataTable.("RATE.POut") = pout;
dataTable.("RATE.YOut") = yout;
dataTable.u_motor_1 = 0.5 + zeros(numel(t), 1);
dataTable.u_motor_2 = 0.5 + zeros(numel(t), 1);
dataTable.u_motor_3 = 0.5 + zeros(numel(t), 1);
dataTable.u_motor_4 = 0.5 + zeros(numel(t), 1);
dataTable.motor_saturation_flag = false(numel(t), 1);
end

function registry = makeRegistry()
registry = table( ...
    ["good_overlap_a"; "good_overlap_b"; "bad_low_input"; "bad_type"], ...
    repmat("synthetic.BIN", 4, 1), ...
    ["В-10"; "В-10"; "В-10"; "В-06"], ...
    ["roll_response_candidate"; "roll_response_candidate"; "roll_response_candidate"; "climb_candidate"], ...
    [1; 1.5; 8; 3], ...
    [5; 5.5; 10; 6], ...
    [4; 4; 2; 3], ...
    [30; 30; 30; 30], ...
    [0; 0; 0; 1], ...
    [0; 0; 0; 0], ...
    [5; 10; 0; 0], ...
    [0; 0; 0; 0], ...
    [0; 0; 0; 0], ...
    [0; 0; 0; 0], ...
    repmat("синтетика", 4, 1), ...
    [0.8; 0.9; 0.1; 0.5], ...
    repmat("синтетика", 4, 1), ...
    'VariableNames', registryNames());
end

function names = registryNames()
names = { ...
    'segment_id', ...
    'log_file', ...
    'candidate_validation_case_id', ...
    'segment_type', ...
    't_start_s', ...
    't_end_s', ...
    'duration_s', ...
    'mean_altitude_m', ...
    'mean_vertical_speed_mps', ...
    'mean_horizontal_speed_mps', ...
    'roll_rms_deg', ...
    'pitch_rms_deg', ...
    'yaw_rate_rms_deg_s', ...
    'motor_saturation_percent', ...
    'data_quality_flags', ...
    'score', ...
    'notes'};
end

function settings = makeSettings()
settings = struct();
settings.min_duration_s = 2;
settings.max_duration_s = 12;
settings.min_input_std = 0.02;
settings.min_rate_std_deg_s = 1;
settings.max_nan_percent = 5;
settings.max_motor_saturation_percent = 5;
settings.min_time_gap_between_segments_s = 1;
settings.max_condition_number = Inf;
settings.candidate_types_for_rate_identification = [
    "roll_response_candidate"
    "pitch_response_candidate"
    "yaw_response_candidate"
    "hover_candidate"
    ];
settings.exclude_candidate_types_for_rate_identification = [
    "climb_candidate"
    "descent_candidate"
    "thrust_response_candidate"
    ];
end
