classdef TestRepositoryFiles < matlab.unittest.TestCase
    % Проверка обязательной структуры репозитория для PR №1.

    methods (Test)
        function testRequiredProjectStructure(testCase)
            projectRoot = fileparts(fileparts(mfilename('fullpath')));
            requiredPaths = [
                "matlab/+copter"
                "matlab/+copter/+config"
                "matlab/+copter/+data"
                "matlab/+copter/+models"
                "matlab/+copter/+identification"
                "matlab/+copter/+validation"
                "matlab/+copter/+reports"
                "matlab/+copter/+utils"
                "config/vehicle_qc_ardupilot_v0.json"
                "config/validation_basis_v0.json"
                "docs/model_description.md"
                "docs/validation_by_log_method.md"
                "docs/data_contract.md"
                "docs/simulink_preparation.md"
                "data/raw/ardupilot/bin/README.md"
                "data/raw/ardupilot/bin/manifest_template.json"
                "docs/validation_basis/README.md"
                "result/README.md"
                "matlab/+copter/+models/ModelRate.m"
                "matlab/+copter/+models/Model6DOF.m"
                "matlab/+copter/+validation/validateByLog.m"
                "matlab/+copter/+validation/buildValidationMatrix.m"
                "matlab/+copter/+reports/writeMarkdownReport.m"
                "matlab/+copter/+reports/writeBinAnalysisSummary.m"
                "matlab/+copter/+reports/writeMissingBinLogsReport.m"
                "matlab/+copter/+data/preprocessLogData.m"
                "matlab/+copter/+data/inspectBinLog.m"
                "matlab/+copter/+data/readBinLog.m"
                "matlab/+copter/+data/parseDataFlashFmt.m"
                "matlab/+copter/+data/decodeDataFlashMessage.m"
                "matlab/+copter/+data/dataFlashFormatMap.m"
                "matlab/+copter/+data/buildLogChannelInventory.m"
                "config/log_manifest_v0.json"
                "config/segment_detection_v0.json"
                "config/model_rate_identification_v0.json"
                "config/segment_curation_v0.json"
                "scripts/analyze_bin_logs.m"
                "scripts/07_analyze_bin_logs.m"
                "scripts/08_extract_segments_and_fit_rate_model.m"
                "scripts/extract_segments_and_fit_rate_model.m"
                "scripts/09_curate_segments_and_refit_rate_model.m"
                "scripts/curate_segments_and_refit_rate_model.m"
                "matlab/+copter/+data/buildProcessedTimetableFromBin.m"
                "matlab/+copter/+data/extractFlightSignals.m"
                "matlab/+copter/+data/computeDerivedSignals.m"
                "matlab/+copter/+data/synchronizeLogMessages.m"
                "matlab/+copter/+data/normalizeMotorOutputsFromRCOU.m"
                "matlab/+copter/+data/diagnoseSignalUnits.m"
                "matlab/+copter/+data/diagnoseTimebase.m"
                "matlab/+copter/+models/ModelRateDiscrete.m"
                "matlab/+copter/+models/simulateRateDiscrete.m"
                "matlab/+copter/+validation/detectValidationSegments.m"
                "matlab/+copter/+validation/scoreValidationCaseCandidates.m"
                "matlab/+copter/+validation/buildSegmentRegistry.m"
                "matlab/+copter/+validation/splitSegmentsForIdentification.m"
                "matlab/+copter/+validation/curateValidationSegments.m"
                "matlab/+copter/+validation/removeOverlappingSegments.m"
                "matlab/+copter/+validation/computeSegmentExcitationMetrics.m"
                "matlab/+copter/+validation/rankSegmentsForRateIdentification.m"
                "matlab/+copter/+validation/splitCuratedSegments.m"
                "matlab/+copter/+identification/fitRateModelFromSegments.m"
                "matlab/+copter/+identification/fitRateModelDiscreteFromSegments.m"
                "matlab/+copter/+identification/fitCuratedRateModels.m"
                "matlab/+copter/+validation/validateRateModelOnSegments.m"
                "matlab/+copter/+validation/validateRateModelDiscreteOnSegments.m"
                "matlab/+copter/+validation/compareRateModelVariants.m"
                "matlab/+copter/+reports/writeSegmentInventoryReport.m"
                "matlab/+copter/+reports/writeRateIdentificationReport.m"
                "tests/TestDataFlashParserSynthetic.m"
                "tests/TestLogManifest.m"
                "tests/TestBinToProcessedTimetable.m"
                "tests/TestValidationSegmentDetectionSynthetic.m"
                "tests/TestRateIdentificationFromSegmentsSynthetic.m"
                "tests/TestTextFileLineEndings.m"
                "tests/TestSegmentCurationSynthetic.m"
                "tests/TestMetricRobustness.m"
                "tests/TestSignalUnitDiagnostics.m"
                "tests/TestTimebaseDiagnostics.m"
                "tests/TestRateDiscreteModelSynthetic.m"
                "tests/TestCuratedRateIdentificationSynthetic.m"
                ];

            for index = 1:numel(requiredPaths)
                pathToCheck = fullfile(projectRoot, requiredPaths(index));
                message = sprintf('Отсутствует обязательный путь: %s', pathToCheck);
                testCase.verifyTrue(isfolder(pathToCheck) || isfile(pathToCheck), message);
            end
        end
    end
end
