classdef TestRateIdentificationFromSegmentsSynthetic < matlab.unittest.TestCase
    % Проверка идентификации ModelRate по синтетическим участкам.

    methods (Test)
        function testRateIdentificationFromSegments(testCase)
            [processedData, trueModel] = makeSyntheticRateData();
            registry = makeSegmentRegistry();
            config = copter.config.defaultVehicleConfig();
            [identifiedModel, fitReport, warnings] = copter.identification.fitRateModelFromSegments(processedData, registry(1, :), config);
            validationReport = copter.validation.validateRateModelOnSegments(identifiedModel, processedData, registry(2, :), config);

            testCase.verifySize(identifiedModel.A, [3, 3]);
            testCase.verifySize(identifiedModel.B, [3, 3]);
            testCase.verifySize(identifiedModel.c, [3, 1]);
            testCase.verifyFalse(isempty(fitReport));
            testCase.verifyLessThan(norm(diag(identifiedModel.A) - diag(trueModel.A)), 0.35);
            testCase.verifyLessThan(norm(diag(identifiedModel.B) - diag(trueModel.B)), 0.35);
            testCase.verifyTrue(all(validationReport.channelConclusion.mean_fit_percent > 80));
            testCase.verifyClass(warnings, 'string');
        end
    end
end

function [processedData, model] = makeSyntheticRateData()
sampleRateHz = 100;
t = transpose(0:1 / sampleRateHz:40);
A = diag([-1.2, -1.0, -0.8]);
B = diag([2.0, 1.8, 1.4]);
c = [0.01; -0.02; 0.015];
model = copter.models.ModelRate(A, B, c);
u = [
    0.25 * sin(0.6 * t), ...
    0.20 * cos(0.5 * t), ...
    0.18 * sin(0.4 * t)
    ];
omega = zeros(numel(t), 3);

for index = 1:numel(t) - 1
    step = t(index + 1) - t(index);
    state = transpose(omega(index, :));
    input = transpose(u(index, :));
    omega(index + 1, :) = transpose(state + step * copter.models.rhsRateModel(t(index), state, input, model));
end

dataTable = table();
dataTable.t_s = t;
dataTable.("RATE.R_rad_s") = omega(:, 1);
dataTable.("RATE.P_rad_s") = omega(:, 2);
dataTable.("RATE.Y_rad_s") = omega(:, 3);
dataTable.("RATE.R") = rad2deg(omega(:, 1));
dataTable.("RATE.P") = rad2deg(omega(:, 2));
dataTable.("RATE.Y") = rad2deg(omega(:, 3));
dataTable.("RATE.ROut") = u(:, 1);
dataTable.("RATE.POut") = u(:, 2);
dataTable.("RATE.YOut") = u(:, 3);
processedData = table2timetable(dataTable, 'RowTimes', seconds(dataTable.t_s));
end

function registry = makeSegmentRegistry()
registry = table( ...
    ["synthetic_identification"; "synthetic_validation"], ...
    ["synthetic.BIN"; "synthetic.BIN"], ...
    ["В-10"; "В-10"], ...
    ["roll_response_candidate"; "roll_response_candidate"], ...
    [2; 22], ...
    [18; 38], ...
    [16; 16], ...
    [30; 30], ...
    [0; 0], ...
    [0; 0], ...
    [0; 0], ...
    [0; 0], ...
    [0; 0], ...
    [0; 0], ...
    ["синтетика"; "синтетика"], ...
    [1; 1], ...
    ["синтетический участок"; "синтетический участок"], ...
    ["identification"; "validation"], ...
    'VariableNames', { ...
    'segment_id', ...
    'log_file', ...
    'candidate_validation_case_id', ...
    'segment_type', ...
    't_start_s', ...
    't_end_s', ...
    'duration_s', ...
    'mean_altitude_m', ...
    'mean_vertical_speed_mps', ...
    'mean_horizontal_speed_mps', ...
    'roll_rms_deg', ...
    'pitch_rms_deg', ...
    'yaw_rate_rms_deg_s', ...
    'motor_saturation_percent', ...
    'data_quality_flags', ...
    'score', ...
    'notes', ...
    'split_role'});
end
