function inventory = buildLogChannelInventory(summaries)
% Формирует реестр фактического состава каналов бортовых журналов.

summaryList = normalizeSummaryList(summaries);
inventory = emptyInventoryTable();

for summaryIndex = 1:numel(summaryList)
    summary = summaryList(summaryIndex);
    if ~isfield(summary, 'messages') || isempty(summary.messages)
        continue;
    end

    messageTable = summary.messages;
    for rowIndex = 1:height(messageTable)
        messageName = string(messageTable.message_name(rowIndex));
        row = table( ...
            string(summary.file_name), ...
            messageName, ...
            messageTable.message_type_id(rowIndex), ...
            messageTable.count(rowIndex), ...
            messageTable.has_TimeUS(rowIndex), ...
            messageTable.first_TimeUS(rowIndex), ...
            messageTable.last_TimeUS(rowIndex), ...
            messageTable.estimated_rate_hz(rowIndex), ...
            string(messageTable.fields(rowIndex)), ...
            isUsefulForRateModel(messageName), ...
            isUsefulForModel6DOF(messageName), ...
            isUsefulForBatteryModel(messageName), ...
            isUsefulForValidation(messageName), ...
            warningsForMessage(summary, messageName), ...
            'VariableNames', inventory.Properties.VariableNames);
        inventory = [inventory; row];
    end
end
end

function summaryList = normalizeSummaryList(summaries)
if isempty(summaries)
    summaryList = struct([]);
elseif iscell(summaries)
    summaryList = [summaries{:}];
else
    summaryList = summaries;
end
end

function value = isUsefulForRateModel(messageName)
name = upper(messageName);
value = any(name == ["RATE", "RCOU", "ATT"]);
end

function value = isUsefulForModel6DOF(messageName)
name = upper(messageName);
value = any(name == ["ATT", "RATE", "RCOU", "GPS", "POS", "IMU", "ACC", "GYR", "BARO"]) || startsWith(name, "XKF");
end

function value = isUsefulForBatteryModel(messageName)
name = upper(messageName);
value = name == "BAT" || startsWith(name, "ESC");
end

function value = isUsefulForValidation(messageName)
name = upper(messageName);
value = any(name == ["ATT", "RATE", "RCOU", "BAT", "GPS", "POS", "MODE"]) || startsWith(name, "ESC") || startsWith(name, "XKF");
end

function text = warningsForMessage(summary, messageName)
if ~isfield(summary, 'warnings') || isempty(summary.warnings)
    text = "";
    return;
end

related = summary.warnings(contains(summary.warnings, messageName));
if isempty(related)
    text = "";
else
    text = strjoin(related, " ");
end
end

function inventory = emptyInventoryTable()
inventory = table( ...
    strings(0, 1), ...
    strings(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    false(0, 1), ...
    NaN(0, 1), ...
    NaN(0, 1), ...
    NaN(0, 1), ...
    strings(0, 1), ...
    false(0, 1), ...
    false(0, 1), ...
    false(0, 1), ...
    false(0, 1), ...
    strings(0, 1), ...
    'VariableNames', { ...
    'log_file', ...
    'message_name', ...
    'message_type_id', ...
    'count', ...
    'has_TimeUS', ...
    'first_TimeUS', ...
    'last_TimeUS', ...
    'estimated_rate_hz', ...
    'fields', ...
    'useful_for_model_rate', ...
    'useful_for_model6dof', ...
    'useful_for_battery_model', ...
    'useful_for_validation', ...
    'warnings'});
end
