function registry = buildSegmentRegistry(processedData, segments, logFile)
% Формирует реестр участков-кандидатов валидационного базиса.

if nargin < 3
    logFile = "";
end

if isempty(segments)
    registry = emptyRegistry();
    return;
end

dataTable = localTable(processedData);
rowCount = height(segments);
registry = emptyRegistry();

for index = 1:rowCount
    mask = dataTable.t_s >= segments.t_start_s(index) & dataTable.t_s <= segments.t_end_s(index);
    segmentData = dataTable(mask, :);
    row = table( ...
        string(segments.segment_id(index)), ...
        string(logFile), ...
        string(segments.candidate_validation_case_id(index)), ...
        string(segments.segment_type(index)), ...
        segments.t_start_s(index), ...
        segments.t_end_s(index), ...
        segments.duration_s(index), ...
        meanColumn(segmentData, "altitude_m"), ...
        meanColumn(segmentData, "vertical_speed_mps"), ...
        meanColumn(segmentData, "horizontal_speed_mps"), ...
        rmsColumn(segmentData, "ATT.Roll"), ...
        rmsColumn(segmentData, "ATT.Pitch"), ...
        rmsColumn(segmentData, "RATE.Y"), ...
        100 * meanColumn(segmentData, "motor_saturation_flag"), ...
        qualityFlags(segmentData), ...
        segments.score(index), ...
        buildNotes(segments, index, logFile), ...
        'VariableNames', emptyRegistry().Properties.VariableNames);
    registry = [registry; row];
end
end

function text = buildNotes(segments, index, logFile)
notes = string(segments.reason(index));
if strlength(string(segments.limitations(index))) > 0
    notes = notes + " Ограничения: " + string(segments.limitations(index));
end

if string(logFile) == "VB-01.alt_50m.BIN" && string(segments.candidate_validation_case_id(index)) == "В-01"
    notes = notes + " Имя файла указывает alt_50m, а случай В-01 в ВБ задан как висение на высоте 30 м; фактическую высоту требуется подтвердить по журналу.";
end

text = notes;
end

function flags = qualityFlags(segmentData)
if isempty(segmentData)
    flags = "нет данных";
    return;
end

nanPercent = 100 * mean(any(ismissing(segmentData), 2), 'omitnan');
saturationPercent = 100 * meanColumn(segmentData, "motor_saturation_flag");
flags = "пропуски " + string(round(nanPercent, 2)) + " %, насыщение RCOU " + string(round(saturationPercent, 2)) + " %";
end

function value = meanColumn(dataTable, variableName)
if isempty(dataTable) || ~hasVariable(dataTable, variableName)
    value = NaN;
else
    value = mean(double(dataTable.(variableName)), 'omitnan');
end
end

function value = rmsColumn(dataTable, variableName)
if isempty(dataTable) || ~hasVariable(dataTable, variableName)
    value = NaN;
else
    value = sqrt(mean(double(dataTable.(variableName)) .^ 2, 'omitnan'));
end
end

function result = hasVariable(dataTable, variableName)
result = any(string(dataTable.Properties.VariableNames) == string(variableName));
end

function dataTable = localTable(dataSet)
if istimetable(dataSet)
    dataTable = timetable2table(dataSet, 'ConvertRowTimes', false);
else
    dataTable = dataSet;
end
end

function registry = emptyRegistry()
registry = table( ...
    strings(0, 1), ...
    strings(0, 1), ...
    strings(0, 1), ...
    strings(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    zeros(0, 1), ...
    NaN(0, 1), ...
    NaN(0, 1), ...
    NaN(0, 1), ...
    NaN(0, 1), ...
    NaN(0, 1), ...
    NaN(0, 1), ...
    NaN(0, 1), ...
    strings(0, 1), ...
    NaN(0, 1), ...
    strings(0, 1), ...
    'VariableNames', { ...
    'segment_id', ...
    'log_file', ...
    'candidate_validation_case_id', ...
    'segment_type', ...
    't_start_s', ...
    't_end_s', ...
    'duration_s', ...
    'mean_altitude_m', ...
    'mean_vertical_speed_mps', ...
    'mean_horizontal_speed_mps', ...
    'roll_rms_deg', ...
    'pitch_rms_deg', ...
    'yaw_rate_rms_deg_s', ...
    'motor_saturation_percent', ...
    'data_quality_flags', ...
    'score', ...
    'notes'});
end
