function comparison = compareRateModelVariants(continuousModel, discreteModel, processedData, validationSegments, config)
% Сравнивает непрерывный и дискретный варианты модели угловых скоростей.

if nargin < 5 || isempty(config)
    config = copter.config.defaultVehicleConfig();
end

continuousReport = copter.validation.validateRateModelOnSegments( ...
    continuousModel, processedData, validationSegments, config);
discreteReport = copter.validation.validateRateModelDiscreteOnSegments( ...
    discreteModel, processedData, validationSegments, config);

comparison = [
    summarizeVariant(continuousReport.metricsBySegment, "continuous ModelRate", config)
    summarizeVariant(discreteReport.metricsBySegment, "discrete ModelRateDiscrete", config)
    ];
end

function summary = summarizeVariant(metricsTable, variantName, config)
axes = ["RATE.R"; "RATE.P"; "RATE.Y"];
criteria = [
    config.criteria.rate_roll_pitch_fit_min_percent
    config.criteria.rate_roll_pitch_fit_min_percent
    config.criteria.rate_yaw_fit_min_percent
    ];

summary = table();
for index = 1:numel(axes)
    axisName = axes(index);
    if isempty(metricsTable)
        axisMetrics = table();
    else
        mask = metricsTable.axis == axisName;
        axisMetrics = metricsTable(mask, :);
    end

    if isempty(axisMetrics)
        row = emptyRow(axisName, variantName);
        summary = [summary; row];
        continue;
    end

    validMask = false(height(axisMetrics), 1);
    if ~isempty(axisMetrics) && any(string(axisMetrics.Properties.VariableNames) == "valid_metric_flag")
        validMask = axisMetrics.valid_metric_flag;
    end

    fitValue = mean(axisMetrics.fit_percent(validMask), 'omitnan');
    passCriterion = isfinite(fitValue) && fitValue >= criteria(index);
    row = table( ...
        axisName, ...
        variantName, ...
        mean(axisMetrics.rmse_rad_s, 'omitnan'), ...
        mean(axisMetrics.mae_rad_s, 'omitnan'), ...
        mean(axisMetrics.max_abs_rad_s, 'omitnan'), ...
        mean(axisMetrics.nrmse, 'omitnan'), ...
        fitValue, ...
        mean(axisMetrics.correlation(validMask), 'omitnan'), ...
        nnz(validMask), ...
        height(axisMetrics) - nnz(validMask), ...
        passCriterion, ...
        conclusionText(passCriterion, fitValue), ...
        'VariableNames', { ...
        'axis', ...
        'model_variant', ...
        'RMSE', ...
        'MAE', ...
        'max_abs_error', ...
        'NRMSE', ...
        'FIT', ...
        'correlation', ...
        'number_of_valid_segments', ...
        'number_of_invalid_metric_segments', ...
        'pass_preliminary_criterion', ...
        'conclusion'});
    summary = [summary; row];
end
end

function row = emptyRow(axisName, variantName)
row = table( ...
    axisName, ...
    variantName, ...
    NaN, ...
    NaN, ...
    NaN, ...
    NaN, ...
    NaN, ...
    NaN, ...
    0, ...
    0, ...
    false, ...
    "нет участков validation", ...
    'VariableNames', { ...
    'axis', ...
    'model_variant', ...
    'RMSE', ...
    'MAE', ...
    'max_abs_error', ...
    'NRMSE', ...
    'FIT', ...
    'correlation', ...
    'number_of_valid_segments', ...
    'number_of_invalid_metric_segments', ...
    'pass_preliminary_criterion', ...
    'conclusion'});
end

function text = conclusionText(passCriterion, fitValue)
if passCriterion
    text = "предварительный критерий выполнен";
elseif ~isfinite(fitValue)
    text = "показатель соответствия не применим для выбранных участков";
else
    text = "предварительный критерий не выполнен";
end
end
